#!/usr/bin/env bash
# Reject commit messages that attribute authorship to AI assistants.
#
# Used as a `commit-msg` hook (see .pre-commit-config.yaml). The first
# argument is the path to the file holding the commit message (git's
# convention for commit-msg hooks).
#
# Patterns rejected:
#   - `Co-Authored-By: ... claude ...` (any case)
#   - `Co-Authored-By: ... anthropic ...` (any case)
#   - `Generated with Claude` / `Generated by Claude` style trailers
#   - bare lines mentioning Anthropic in a trailer position

set -euo pipefail

msg_file="${1:?usage: $0 <commit-msg-file>}"

if [[ ! -f "$msg_file" ]]; then
    echo "check-no-ai-attribution: commit-msg file not found: $msg_file" >&2
    exit 1
fi

if grep -iqE '^Co-Authored-By:.*(claude|anthropic)' "$msg_file"; then
    echo "✗ Commit rejected: Co-Authored-By trailer references Claude/Anthropic." >&2
    echo "  Strip the trailer and try again." >&2
    exit 1
fi

if grep -iqE '(generated|written|authored).*(by|with).*(claude|anthropic)' "$msg_file"; then
    echo "✗ Commit rejected: AI-generation attribution detected." >&2
    echo "  Remove the mention and try again." >&2
    exit 1
fi

exit 0
